// ============================================
// FILING GUIDE — STEP-BY-STEP GUIDE GENERATOR
// Static guide data per authority type
// ============================================

import type { FilingGuide, AuthorityType, DocumentChecklistItem, FilingGuideStep } from '@/types';

/**
 * Get a step-by-step filing guide for the given authority type.
 * All guides are static (deterministic) — no AI calls.
 */
export function getFilingGuide(authorityType: AuthorityType): FilingGuide {
  switch (authorityType) {
    case 'consumer_forum_district':
    case 'consumer_forum_state':
    case 'consumer_forum_national':
      return getConsumerForumGuide(authorityType);
    case 'rbi_ombudsman':
      return getRBIOmbudsmanGuide();
    case 'rera_state':
      return getRERAGuide();
    case 'insurance_ombudsman':
      return getInsuranceOmbudsmanGuide();
    case 'labour_commissioner':
      return getLabourGuide();
    default:
      return getConsumerForumGuide('consumer_forum_district');
  }
}

function getConsumerForumGuide(level: AuthorityType): FilingGuide {
  const levelName = level === 'consumer_forum_national' ? 'National Commission'
    : level === 'consumer_forum_state' ? 'State Commission'
    : 'District Forum';

  const steps: FilingGuideStep[] = [
    {
      step_number: 1, title: 'Register on e-Daakhil', action_type: 'navigate',
      description: 'Go to edaakhil.nic.in and create an account with your mobile number and email.',
      url: 'https://edaakhil.nic.in', form_fields: null, copy_paste_data: null,
      screenshot_description: 'Registration page — enter name, mobile, email, and create password',
      tips: ['Use the same mobile number you will use for OTP verification', 'Keep your login credentials safe'],
    },
    {
      step_number: 2, title: 'Click "File New Case"', action_type: 'navigate',
      description: 'After login, click "File New Case" on the dashboard. Select "Consumer Complaint" as case type.',
      url: 'https://edaakhil.nic.in', form_fields: null, copy_paste_data: null,
      screenshot_description: null,
      tips: ['Select the correct state and district of the Forum where you want to file'],
    },
    {
      step_number: 3, title: 'Fill Complainant Details', action_type: 'fill_form',
      description: 'Enter your full name, address, phone, and email. Upload your ID proof.',
      url: null,
      form_fields: [
        { field_name: 'Name', field_value: '[Your full name as on ID]', field_location: 'Complainant section', notes: null },
        { field_name: 'Address', field_value: '[Your complete address]', field_location: 'Complainant section', notes: 'Include PIN code' },
        { field_name: 'Mobile', field_value: '[Your mobile number]', field_location: 'Complainant section', notes: null },
      ],
      copy_paste_data: null, screenshot_description: null,
      tips: ['Name must match your ID proof exactly', 'Address should be in the jurisdiction of the Forum'],
    },
    {
      step_number: 4, title: 'Fill Opposite Party Details', action_type: 'fill_form',
      description: 'Enter the respondent company/person name, registered address, and any other known details.',
      url: null,
      form_fields: [
        { field_name: 'Name', field_value: '[Company/Person name]', field_location: 'Opposite Party section', notes: 'Use registered name, not brand name' },
        { field_name: 'Address', field_value: '[Registered office address]', field_location: 'Opposite Party section', notes: 'Check on MCA portal for company registered address' },
      ],
      copy_paste_data: null, screenshot_description: null,
      tips: ['If company, check the registered name on mca.gov.in', 'You can add multiple opposite parties'],
    },
    {
      step_number: 5, title: 'Upload Complaint Document', action_type: 'upload',
      description: 'Upload the complaint document (PDF) generated by ClauseWall. Also upload the affidavit and supporting documents.',
      url: null, form_fields: null, copy_paste_data: null, screenshot_description: null,
      tips: ['All documents must be in PDF format', 'Keep file size under 10MB each', 'Upload the synopsis as the first document'],
    },
    {
      step_number: 6, title: 'Pay Filing Fee', action_type: 'pay',
      description: 'Pay the court fee using the online payment gateway (if applicable). Fee depends on claim amount.',
      url: null, form_fields: null, copy_paste_data: null, screenshot_description: null,
      tips: ['Claims up to ₹5 lakh: No fee', 'Keep the payment receipt for your records', 'DD should be in favor of Registrar of the Forum'],
    },
    {
      step_number: 7, title: 'Submit & Note Case Number', action_type: 'submit',
      description: 'Review all details and submit. Note down the case number/diary number for tracking.',
      url: null, form_fields: null, copy_paste_data: null, screenshot_description: null,
      tips: ['Save the confirmation page as PDF', 'Note the case/diary number — you will need it for all future communications', 'You will receive SMS/email confirmation'],
    },
    {
      step_number: 8, title: 'Serve Notice to Opposite Party', action_type: 'note_down',
      description: 'Send a copy of the complaint to the opposite party via Registered Post AD. Keep the postal receipt.',
      url: null, form_fields: null, copy_paste_data: null, screenshot_description: null,
      tips: ['Use Registered Post with Acknowledgement Due (RPAD)', 'Keep the postal receipt and AD card — file these with the Forum', 'Allow 30 days for response'],
    },
  ];

  const checklist: DocumentChecklistItem[] = [
    { document: 'Complaint (3 copies: Forum + each Opposite Party + self)', required: true, available: true, how_to_get: 'Generated by ClauseWall', notes: 'Print on A4 paper' },
    { document: 'Affidavit (notarized)', required: true, available: true, how_to_get: 'Generated by ClauseWall — get it notarized', notes: 'Notary fee: ₹50-₹200' },
    { document: 'Synopsis / Index', required: false, available: true, how_to_get: 'Generated by ClauseWall', notes: null },
    { document: 'Copy of contract/agreement', required: true, available: true, how_to_get: 'The document you uploaded to ClauseWall', notes: null },
    { document: 'ID proof (Aadhaar/PAN/Passport)', required: true, available: false, how_to_get: 'Self-attested photocopy', notes: null },
    { document: 'Address proof', required: true, available: false, how_to_get: 'Electricity bill / bank statement / Aadhaar', notes: null },
    { document: 'Payment receipts (if any)', required: false, available: false, how_to_get: 'Bank statements, UPI screenshots, receipts', notes: 'Important for calculating claim amount' },
    { document: 'Court fee stamp / DD / online payment receipt', required: true, available: false, how_to_get: 'Available at Forum or online via e-Daakhil', notes: 'Not needed if claim ≤ ₹5 lakh' },
    { document: 'Communication evidence (emails, messages)', required: false, available: false, how_to_get: 'Screenshots + printouts', notes: 'Helps establish timeline' },
  ];

  return {
    authority_type: level,
    authority_name: levelName,
    portal_url: 'https://edaakhil.nic.in',
    total_steps: steps.length,
    steps,
    documents_checklist: checklist,
    estimated_time: '45-60 minutes (online)',
    important_notes: [
      'File within 2 years of the cause of action (CPA 2019 §69)',
      'e-Daakhil is available 24/7 — you can file at any time',
      'Physical filing is also accepted at the Forum during working hours',
      'You do NOT need a lawyer — you can argue your own case',
    ],
    common_mistakes: [
      'Using company brand name instead of registered company name',
      'Not attaching notarized affidavit',
      'Filing at the wrong Forum (must be where you reside or cause of action arose)',
      'Not serving notice to the opposite party via RPAD',
      'Missing the 2-year limitation period',
    ],
    helpline: '1800-11-4000 (National Consumer Helpline, toll-free)',
  };
}

function getRBIOmbudsmanGuide(): FilingGuide {
  return {
    authority_type: 'rbi_ombudsman',
    authority_name: 'RBI Integrated Ombudsman',
    portal_url: 'https://cms.rbi.org.in',
    total_steps: 5,
    steps: [
      { step_number: 1, title: 'Complain to Your Bank First', action_type: 'note_down', description: 'Before filing with RBI, you MUST first complain to your bank and wait 30 days. If the bank rejects or does not respond within 30 days, you can approach the RBI Ombudsman.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Keep the complaint reference number from the bank', 'Email complaints leave a paper trail — preferred'] },
      { step_number: 2, title: 'Go to CMS Portal', action_type: 'navigate', description: 'Visit cms.rbi.org.in and click "File a Complaint".', url: 'https://cms.rbi.org.in', form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['No registration needed — you can file directly'] },
      { step_number: 3, title: 'Select Complaint Category', action_type: 'fill_form', description: 'Choose the entity type (Bank/NBFC/Payment System) and category of complaint.', url: null, form_fields: [{ field_name: 'Entity Type', field_value: 'Bank / NBFC / Payment System Participant', field_location: 'Category page', notes: null }], copy_paste_data: null, screenshot_description: null, tips: ['Choose the most specific category available'] },
      { step_number: 4, title: 'Fill Complaint Details', action_type: 'fill_form', description: 'Enter bank details, account number, complaint details, and upload supporting documents.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Attach the bank rejection letter if available', 'Provide exact dates and transaction details'] },
      { step_number: 5, title: 'Submit & Track', action_type: 'submit', description: 'Submit and note the complaint number. Track status on the same portal.', url: 'https://cms.rbi.org.in', form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Resolution typically within 30 days', 'You can escalate to the Appellate Authority if unsatisfied'] },
    ],
    documents_checklist: [
      { document: 'Evidence of complaint to bank (email/letter)', required: true, available: false, how_to_get: 'First complain to your bank in writing', notes: null },
      { document: 'Bank rejection letter (if any)', required: false, available: false, how_to_get: 'Request from bank', notes: null },
      { document: 'Account statements', required: false, available: false, how_to_get: 'Download from netbanking', notes: null },
      { document: 'Contract/agreement with bank', required: true, available: true, how_to_get: 'The document you uploaded to ClauseWall', notes: null },
    ],
    estimated_time: '15-20 minutes',
    important_notes: ['Completely FREE — no fee at any stage', 'Must first complain to bank and wait 30 days', 'Can also call 14448 to file by phone'],
    common_mistakes: ['Not complaining to bank first', 'Not waiting 30 days for bank response'],
    helpline: '14448 (RBI Ombudsman toll-free helpline)',
  };
}

function getRERAGuide(): FilingGuide {
  return {
    authority_type: 'rera_state',
    authority_name: 'State RERA Authority',
    portal_url: null,
    total_steps: 5,
    steps: [
      { step_number: 1, title: 'Register on State RERA Portal', action_type: 'navigate', description: 'Go to your state RERA website and register as a complainant.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Each state has its own RERA portal'] },
      { step_number: 2, title: 'Fill Complaint Form', action_type: 'fill_form', description: 'Enter project details, builder information, and specific complaint.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['You need the RERA registration number of the project'] },
      { step_number: 3, title: 'Upload Documents', action_type: 'upload', description: 'Upload sale agreement, payment receipts, builder correspondence, and complaint document.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['All documents must be in PDF format'] },
      { step_number: 4, title: 'Pay Filing Fee', action_type: 'pay', description: 'Pay the RERA filing fee (₹1,000 - ₹5,000 depending on state).', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Keep the payment receipt'] },
      { step_number: 5, title: 'Submit & Track', action_type: 'submit', description: 'Submit and note the case number for tracking.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Hearing notice will be sent to your registered email/phone'] },
    ],
    documents_checklist: [
      { document: 'Sale/purchase agreement', required: true, available: true, how_to_get: 'The document you uploaded', notes: null },
      { document: 'Payment receipts to builder', required: true, available: false, how_to_get: 'Bank statements, cheque copies', notes: null },
      { document: 'Builder brochure/marketing material', required: false, available: false, how_to_get: 'Save from website or physical copies', notes: null },
      { document: 'Correspondence with builder', required: false, available: false, how_to_get: 'Emails, letters, WhatsApp messages', notes: null },
      { document: 'ID and address proof', required: true, available: false, how_to_get: 'Aadhaar/PAN card', notes: null },
    ],
    estimated_time: '30-45 minutes',
    important_notes: ['File within 1 year of possession/discovery of defect', 'RERA orders are enforceable as court decrees'],
    common_mistakes: ['Filing for a project not registered under RERA', 'Not mentioning RERA registration number'],
    helpline: null,
  };
}

function getInsuranceOmbudsmanGuide(): FilingGuide {
  return {
    authority_type: 'insurance_ombudsman',
    authority_name: 'Insurance Ombudsman',
    portal_url: 'https://igms.irda.gov.in',
    total_steps: 4,
    steps: [
      { step_number: 1, title: 'Register on IGMS Portal', action_type: 'navigate', description: 'Go to igms.irda.gov.in and register with your policy details.', url: 'https://igms.irda.gov.in', form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['You need your policy number and insurer name'] },
      { step_number: 2, title: 'First File with Insurer via IGMS', action_type: 'fill_form', description: 'File the complaint against the insurer first via IGMS. Wait 15 days for response.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Keep the IGMS complaint number'] },
      { step_number: 3, title: 'Escalate to Insurance Ombudsman', action_type: 'fill_form', description: 'If insurer rejects or does not respond in 15 days, escalate to the Ombudsman via the same IGMS portal.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Claims must be ≤ ₹30 lakh for Ombudsman jurisdiction'] },
      { step_number: 4, title: 'Attend Hearing (if needed)', action_type: 'physical_visit', description: 'The Ombudsman may invite you for a hearing. Attend with all documents.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Ombudsman decision is binding on the insurer'] },
    ],
    documents_checklist: [
      { document: 'Insurance policy document', required: true, available: true, how_to_get: 'Your uploaded document', notes: null },
      { document: 'Claim rejection letter from insurer', required: true, available: false, how_to_get: 'Request from insurer', notes: null },
      { document: 'Medical records (for health claims)', required: false, available: false, how_to_get: null, notes: null },
      { document: 'FIR copy (for theft/accident)', required: false, available: false, how_to_get: null, notes: null },
    ],
    estimated_time: '20-30 minutes',
    important_notes: ['Completely FREE', 'Must first complain to insurer via IGMS', 'Claims above ₹30 lakh go to Consumer Forum'],
    common_mistakes: ['Not first complaining to insurer', 'Filing for claims above ₹30 lakh'],
    helpline: '155255 (IGMS Helpline)',
  };
}

function getLabourGuide(): FilingGuide {
  return {
    authority_type: 'labour_commissioner',
    authority_name: 'Labour Commissioner',
    portal_url: null,
    total_steps: 4,
    steps: [
      { step_number: 1, title: 'Write Complaint Application', action_type: 'note_down', description: 'Write a detailed application addressed to the Labour Commissioner of your district/state.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Use the complaint document generated by ClauseWall'] },
      { step_number: 2, title: 'Visit Labour Commissioner Office', action_type: 'physical_visit', description: 'Visit the Labour Commissioner office to submit the complaint. Carry original documents.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Go during working hours (10 AM - 5 PM)', 'Carry ID proof', 'Ask for an acknowledgement receipt'] },
      { step_number: 3, title: 'Conciliation Process', action_type: 'note_down', description: 'The Labour Commissioner will call both parties for conciliation. Attend all hearings.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['Conciliation is mandatory before tribunal proceedings', 'Bring all evidence to the conciliation meeting'] },
      { step_number: 4, title: 'If Conciliation Fails', action_type: 'note_down', description: 'If conciliation fails, the matter may be referred to Labour Court / Industrial Tribunal.', url: null, form_fields: null, copy_paste_data: null, screenshot_description: null, tips: ['At this stage, consider engaging a lawyer', 'Free legal aid available from DLSA for eligible persons'] },
    ],
    documents_checklist: [
      { document: 'Employment contract/offer letter', required: true, available: true, how_to_get: 'Your uploaded document', notes: null },
      { document: 'Salary slips / bank statements', required: true, available: false, how_to_get: 'From employer or bank', notes: null },
      { document: 'ID proof', required: true, available: false, how_to_get: 'Aadhaar/PAN card', notes: null },
      { document: 'Termination letter (if applicable)', required: false, available: false, how_to_get: 'From employer', notes: null },
    ],
    estimated_time: '1-2 hours (physical visit)',
    important_notes: ['FREE to file — no fee', 'File within 3 years of cause of action', 'Employer attendance is mandatory when summoned'],
    common_mistakes: ['Not having proper employment proof', 'Missing conciliation hearings'],
    helpline: 'Shram Suvidha Portal: shramsuvidha.gov.in',
  };
}
