"use client";

import { motion, MotionValue, useTransform } from "framer-motion";

export default function HeroIncision({ 
  scrollYProgress, 
  isSimplified = false 
}: { 
  scrollYProgress?: MotionValue<number>;
  isSimplified?: boolean;
}) {
  if (isSimplified || !scrollYProgress) {
    return (
      <div className="flex flex-col items-center justify-center text-center mt-12 mb-12">
         <div className="inline-flex items-center gap-2 px-3 py-1 bg-red-500/10 border border-red-500/30 text-red-500 text-xs font-bold uppercase tracking-widest mb-6 rounded-sm">
          <span>India's First Defensive Legal Engine</span>
        </div>
         <h1 className="text-5xl font-black tracking-tighter text-white mb-4 leading-tight">Never Sign <span className="text-red-500">Blindly</span> Again.</h1>
         <p className="text-neutral-400 max-w-xl mx-auto">ClauseWall analyzes your lease, employment bond, or loan in seconds. We find hidden traps and give you the legal ammunition to push back.</p>
      </div>
    );
  }

  // Animation values mapped from 0 to 0.2 of overall scroll
  const containerOpacity = useTransform(scrollYProgress, [0.15, 0.2], [1, 0]);
  const pointerEvents = useTransform(scrollYProgress, (v) => v > 0.2 ? "none" : "auto");

  // Red line strikes
  const lineWidth = useTransform(scrollYProgress, [0, 0.05], ["0%", "100%"]);
  const lineOpacity = useTransform(scrollYProgress, [0.05, 0.1, 0.15], [1, 0.5, 0]);

  // Halves pull apart
  const topY = useTransform(scrollYProgress, [0.05, 0.15], ["0%", "-40vh"]);
  const botY = useTransform(scrollYProgress, [0.05, 0.15], ["0%", "40vh"]);
  const textBlur = useTransform(scrollYProgress, [0, 0.05], ["blur(0px)", "blur(4px)"]);

  // Hero Text reveals in middle
  const heroOpacity = useTransform(scrollYProgress, [0.05, 0.12], [0, 1]);
  const heroScale = useTransform(scrollYProgress, [0.05, 0.12], [0.9, 1]);

  const BackgroundText = () => (
    <div className="text-neutral-600/30 text-justify text-[10px] md:text-[12px] font-mono leading-relaxed select-none max-w-7xl mx-auto">
      {Array(40).fill("THIS AGREEMENT is entered into by and between the parties. User agrees to indemnify and hold harmless the Corporation against all claims. The User waives all rights to participate in a class action lawsuit. Arbitration shall be binding and conducted in a venue solely chosen by the Corporation. All intellectual property generated by the User becomes the immediate and irrevocable property of the Corporation without compensation. ").join("")}
    </div>
  );

  return (
    <motion.div 
      className="absolute inset-0 flex items-center justify-center"
      style={{ opacity: containerOpacity, pointerEvents: pointerEvents as any }}
    >
      <div className="sr-only">
        <h1>Never Sign Blindly Again.</h1>
        <p>ClauseWall is India's first defensive legal engine. We find hidden traps in your contracts.</p>
      </div>

      <motion.div 
        aria-hidden="true"
        className="absolute inset-0 overflow-hidden px-8 flex flex-col justify-center pointer-events-none"
        style={{ clipPath: "inset(0 0 50% 0)", y: topY, filter: textBlur }}
      >
        <BackgroundText />
      </motion.div>

      <motion.div 
        className="absolute top-1/2 left-0 h-[2px] bg-red-500 z-10 -translate-y-1/2 shadow-[0_0_12px_rgba(239,68,68,0.8)] pointer-events-none"
        style={{ width: lineWidth, opacity: lineOpacity }}
      />

      <motion.div 
        aria-hidden="true"
        className="absolute inset-0 overflow-hidden px-8 flex flex-col justify-center pointer-events-none"
        style={{ clipPath: "inset(50% 0 0 0)", y: botY, filter: textBlur }}
      >
        <BackgroundText />
      </motion.div>

      <motion.div 
        className="absolute z-20 text-center px-4"
        style={{ opacity: heroOpacity, scale: heroScale }}
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 bg-red-500/10 border border-red-500/30 text-red-500 text-xs font-bold uppercase tracking-widest mb-6 backdrop-blur-sm rounded-sm">
          <span>India's First Defensive Legal Engine</span>
        </div>
        <h2 className="text-6xl md:text-8xl font-black tracking-tighter leading-none text-white mb-6 font-display">
          Never Sign <br />
          <span className="text-red-500">Blindly</span> Again.
        </h2>
        <p className="text-neutral-400 text-lg md:text-xl max-w-2xl mx-auto font-medium">
          ClauseWall analyzes your lease, employment bond, or loan in seconds. We find hidden traps and give you the legal ammunition to push back.
        </p>
      </motion.div>
      
    </motion.div>
  );
}
