// ============================================
// CONTRACT GENERATOR — AI-Powered Fair Contract Creation
// Uses Groq to generate legally compliant Indian contracts
// ============================================

import { callGroq, GroqMessage } from "@/lib/ai/groq-client";
import {
  CONTRACT_BUILDER_SYSTEM_PROMPT,
  buildContractUserPrompt,
} from "@/lib/ai/contract-builder-prompt";
import { getTemplateConfig } from "@/lib/builder/template-fields";
import {
  ContractTemplateType,
  GeneratedClause,
} from "@/types";

// ============================================
// TYPES
// ============================================

interface AIContractResponse {
  title: string;
  preamble: string;
  clauses: GeneratedClause[];
  signature_block: string;
  witnesses_block: string;
  stamp_paper_note: string;
}

export interface GenerateContractResult {
  success: boolean;
  title: string;
  formatted_text: string;
  clauses: GeneratedClause[];
  stamp_paper_note: string;
  error?: string;
}

// ============================================
// FORMAT CONTRACT TO TEXT
// ============================================

function formatContractToText(response: AIContractResponse): string {
  const lines: string[] = [];

  // Title
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(response.title.toUpperCase());
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("");

  // Preamble
  lines.push(response.preamble);
  lines.push("");
  lines.push("-".repeat(60));
  lines.push("");

  // Clauses
  for (const clause of response.clauses) {
    lines.push(`${clause.number}. ${clause.title.toUpperCase()}`);
    lines.push("");
    lines.push(clause.text);
    if (clause.law_reference) {
      lines.push("");
      lines.push(`    [Legal Basis: ${clause.law_reference}]`);
    }
    lines.push("");
    lines.push("-".repeat(40));
    lines.push("");
  }

  // Signature Block
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("");
  lines.push(response.signature_block);
  lines.push("");

  // Witnesses
  lines.push("");
  lines.push(response.witnesses_block);
  lines.push("");

  // Stamp Paper Note
  if (response.stamp_paper_note) {
    lines.push("");
    lines.push("=".repeat(60));
    lines.push("NOTE ON STAMP PAPER & REGISTRATION:");
    lines.push(response.stamp_paper_note);
    lines.push("=".repeat(60));
  }

  // Footer
  lines.push("");
  lines.push("---");
  lines.push("Generated by ClauseWall — Fair Contract Builder");
  lines.push("This is a template. Please review with a legal professional before signing.");
  lines.push("---");

  return lines.join("\n");
}

// ============================================
// MAIN GENERATOR FUNCTION
// ============================================

export async function generateContract(
  templateType: ContractTemplateType,
  jurisdiction: string,
  values: Record<string, string | number | boolean>
): Promise<GenerateContractResult> {
  try {
    // Validate template type
    const config = getTemplateConfig(templateType);
    if (!config || config.fields.length === 0) {
      return {
        success: false,
        title: "",
        formatted_text: "",
        clauses: [],
        stamp_paper_note: "",
        error: `Template type "${templateType}" is not available yet.`,
      };
    }

    // Validate required fields
    const missingFields: string[] = [];
    for (const field of config.fields) {
      if (field.required) {
        const value = values[field.name];
        if (value === undefined || value === null || value === "") {
          missingFields.push(field.label);
        }
      }
    }

    if (missingFields.length > 0) {
      return {
        success: false,
        title: "",
        formatted_text: "",
        clauses: [],
        stamp_paper_note: "",
        error: `Missing required fields: ${missingFields.join(", ")}`,
      };
    }

    // Build AI prompt
    const userPrompt = buildContractUserPrompt(templateType, jurisdiction, values);

    const messages: GroqMessage[] = [
      { role: "system", content: CONTRACT_BUILDER_SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ];

    console.log(`[ClauseWall Builder] Generating ${templateType} contract for ${jurisdiction}...`);

    // Call Groq with higher token limit for contracts
    const rawResponse = await callGroq(messages, {
      temperature: 0.3,
      maxTokens: 8192,
      retries: 3,
    });

    // Parse response
    let parsed: AIContractResponse;
    try {
      parsed = JSON.parse(rawResponse);
    } catch {
      console.error("[ClauseWall Builder] Failed to parse AI response:", rawResponse.substring(0, 500));
      return {
        success: false,
        title: "",
        formatted_text: "",
        clauses: [],
        stamp_paper_note: "",
        error: "AI returned invalid response. Please try again.",
      };
    }

    // Validate response structure
    if (!parsed.title || !parsed.clauses || !Array.isArray(parsed.clauses) || parsed.clauses.length === 0) {
      return {
        success: false,
        title: "",
        formatted_text: "",
        clauses: [],
        stamp_paper_note: "",
        error: "AI generated incomplete contract. Please try again.",
      };
    }

    // Format to text
    const formattedText = formatContractToText(parsed);

    console.log(
      `[ClauseWall Builder] Generated ${parsed.clauses.length} clauses for ${templateType} contract`
    );

    return {
      success: true,
      title: parsed.title,
      formatted_text: formattedText,
      clauses: parsed.clauses,
      stamp_paper_note: parsed.stamp_paper_note || "",
    };
  } catch (error: any) {
    console.error("[ClauseWall Builder] Generation failed:", error);
    return {
      success: false,
      title: "",
      formatted_text: "",
      clauses: [],
      stamp_paper_note: "",
      error: error.message || "Failed to generate contract. Please try again.",
    };
  }
}