// ============================================
// CONTRACT BUILDER — FIELD DEFINITIONS
// Defines what inputs each contract type needs
// ============================================

import { TemplateConfig, TemplateField, ContractTemplateType } from "@/types";

// ============================================
// INDIAN STATES LIST
// ============================================

export const INDIAN_STATES = [
  { value: "andhra_pradesh", label: "Andhra Pradesh" },
  { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
  { value: "assam", label: "Assam" },
  { value: "bihar", label: "Bihar" },
  { value: "chhattisgarh", label: "Chhattisgarh" },
  { value: "delhi", label: "Delhi (NCT)" },
  { value: "goa", label: "Goa" },
  { value: "gujarat", label: "Gujarat" },
  { value: "haryana", label: "Haryana" },
  { value: "himachal_pradesh", label: "Himachal Pradesh" },
  { value: "jharkhand", label: "Jharkhand" },
  { value: "karnataka", label: "Karnataka" },
  { value: "kerala", label: "Kerala" },
  { value: "madhya_pradesh", label: "Madhya Pradesh" },
  { value: "maharashtra", label: "Maharashtra" },
  { value: "manipur", label: "Manipur" },
  { value: "meghalaya", label: "Meghalaya" },
  { value: "mizoram", label: "Mizoram" },
  { value: "nagaland", label: "Nagaland" },
  { value: "odisha", label: "Odisha" },
  { value: "punjab", label: "Punjab" },
  { value: "rajasthan", label: "Rajasthan" },
  { value: "sikkim", label: "Sikkim" },
  { value: "tamil_nadu", label: "Tamil Nadu" },
  { value: "telangana", label: "Telangana" },
  { value: "tripura", label: "Tripura" },
  { value: "uttar_pradesh", label: "Uttar Pradesh" },
  { value: "uttarakhand", label: "Uttarakhand" },
  { value: "west_bengal", label: "West Bengal" },
  { value: "chandigarh", label: "Chandigarh" },
  { value: "puducherry", label: "Puducherry" },
  { value: "jammu_kashmir", label: "Jammu & Kashmir" },
];

// ============================================
// RENTAL AGREEMENT FIELDS
// ============================================

const rentalFields: TemplateField[] = [
  {
    name: "landlord_name",
    label: "Landlord / Licensor Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Rajesh Kumar Sharma",
    group: "Landlord Details",
  },
  {
    name: "landlord_address",
    label: "Landlord Permanent Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Landlord Details",
  },
  {
    name: "landlord_aadhaar_last4",
    label: "Landlord Aadhaar (Last 4 digits)",
    type: "text",
    required: false,
    placeholder: "e.g., 1234",
    helpText: "Optional — for identification only",
    group: "Landlord Details",
  },
  {
    name: "tenant_name",
    label: "Tenant / Licensee Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Priya Patel",
    group: "Tenant Details",
  },
  {
    name: "tenant_address",
    label: "Tenant Permanent Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Tenant Details",
  },
  {
    name: "tenant_aadhaar_last4",
    label: "Tenant Aadhaar (Last 4 digits)",
    type: "text",
    required: false,
    placeholder: "e.g., 5678",
    helpText: "Optional — for identification only",
    group: "Tenant Details",
  },
  {
    name: "property_address",
    label: "Property Address (Full)",
    type: "textarea",
    required: true,
    placeholder: "Flat No, Building, Street, City, State, PIN",
    group: "Property Details",
  },
  {
    name: "property_type",
    label: "Property Type",
    type: "select",
    required: true,
    options: [
      { value: "residential_flat", label: "Residential Flat / Apartment" },
      { value: "residential_house", label: "Independent House / Villa" },
      { value: "residential_room", label: "Single Room / PG" },
      { value: "commercial_office", label: "Commercial Office Space" },
      { value: "commercial_shop", label: "Commercial Shop" },
      { value: "commercial_warehouse", label: "Warehouse / Godown" },
    ],
    group: "Property Details",
  },
  {
    name: "furnishing",
    label: "Furnishing Status",
    type: "select",
    required: true,
    options: [
      { value: "unfurnished", label: "Unfurnished" },
      { value: "semi_furnished", label: "Semi-Furnished" },
      { value: "fully_furnished", label: "Fully Furnished" },
    ],
    group: "Property Details",
  },
  {
    name: "carpet_area",
    label: "Carpet Area (sq ft)",
    type: "number",
    required: false,
    placeholder: "e.g., 650",
    group: "Property Details",
  },
  {
    name: "monthly_rent",
    label: "Monthly Rent (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 25000",
    group: "Financial Terms",
  },
  {
    name: "security_deposit",
    label: "Security Deposit (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 50000",
    helpText: "Recommended: Max 2 months rent for residential",
    group: "Financial Terms",
  },
  {
    name: "maintenance_included",
    label: "Is Maintenance Included in Rent?",
    type: "select",
    required: true,
    options: [
      { value: "yes", label: "Yes — included in rent" },
      { value: "no", label: "No — tenant pays separately" },
    ],
    group: "Financial Terms",
  },
  {
    name: "maintenance_amount",
    label: "Monthly Maintenance Amount (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 3000",
    helpText: "If maintenance is not included in rent",
    group: "Financial Terms",
  },
  {
    name: "rent_escalation",
    label: "Annual Rent Escalation (%)",
    type: "number",
    required: false,
    placeholder: "e.g., 5",
    helpText: "Standard is 5-10%. Leave blank for no escalation",
    validation: { min: 0, max: 15 },
    group: "Financial Terms",
  },
  {
    name: "rent_due_date",
    label: "Rent Due Date (Day of Month)",
    type: "number",
    required: false,
    placeholder: "e.g., 5",
    default: 5,
    validation: { min: 1, max: 28 },
    group: "Financial Terms",
  },
  {
    name: "agreement_start_date",
    label: "Agreement Start Date",
    type: "date",
    required: true,
    group: "Agreement Terms",
  },
  {
    name: "agreement_duration_months",
    label: "Agreement Duration (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 11",
    default: 11,
    helpText: "11 months is standard (avoids registration requirement)",
    validation: { min: 1, max: 60 },
    group: "Agreement Terms",
  },
  {
    name: "lock_in_months",
    label: "Lock-in Period (Months)",
    type: "number",
    required: false,
    placeholder: "e.g., 3",
    helpText: "Period during which neither party can terminate. 0 = no lock-in",
    validation: { min: 0, max: 12 },
    group: "Agreement Terms",
  },
  {
    name: "notice_period_months",
    label: "Notice Period (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 1",
    default: 1,
    helpText: "Equal for both parties. 1-2 months is standard",
    validation: { min: 1, max: 6 },
    group: "Agreement Terms",
  },
  {
    name: "purpose",
    label: "Purpose of Use",
    type: "select",
    required: true,
    options: [
      { value: "residential", label: "Residential — self/family use" },
      { value: "commercial", label: "Commercial — business use" },
      { value: "home_office", label: "Residential + Home Office" },
    ],
    group: "Agreement Terms",
  },
  {
    name: "pets_allowed",
    label: "Are Pets Allowed?",
    type: "select",
    required: false,
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "with_permission", label: "With prior written permission" },
    ],
    group: "Additional Terms",
  },
  {
    name: "subletting_allowed",
    label: "Is Subletting Allowed?",
    type: "select",
    required: false,
    options: [
      { value: "no", label: "No subletting" },
      { value: "with_permission", label: "With landlord's written consent" },
    ],
    default: "no",
    group: "Additional Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms or Conditions?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Parking included, Gym access, Water supply timings...",
    group: "Additional Terms",
  },
];

// ============================================
// EMPLOYMENT CONTRACT FIELDS
// ============================================

const employmentFields: TemplateField[] = [
  {
    name: "company_name",
    label: "Company / Employer Name",
    type: "text",
    required: true,
    placeholder: "e.g., Acme Technologies Pvt. Ltd.",
    group: "Company Details",
  },
  {
    name: "company_address",
    label: "Company Registered Address",
    type: "textarea",
    required: true,
    placeholder: "Full registered address with PIN code",
    group: "Company Details",
  },
  {
    name: "company_cin",
    label: "Company CIN / Registration Number",
    type: "text",
    required: false,
    placeholder: "e.g., U72200MH2020PTC123456",
    group: "Company Details",
  },
  {
    name: "employee_name",
    label: "Employee Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Ankit Mehta",
    group: "Employee Details",
  },
  {
    name: "employee_address",
    label: "Employee Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Employee Details",
  },
  {
    name: "designation",
    label: "Designation / Job Title",
    type: "text",
    required: true,
    placeholder: "e.g., Senior Software Engineer",
    group: "Role Details",
  },
  {
    name: "department",
    label: "Department",
    type: "text",
    required: false,
    placeholder: "e.g., Engineering",
    group: "Role Details",
  },
  {
    name: "reporting_to",
    label: "Reporting Manager / Designation",
    type: "text",
    required: false,
    placeholder: "e.g., Engineering Manager",
    group: "Role Details",
  },
  {
    name: "work_location",
    label: "Work Location",
    type: "text",
    required: true,
    placeholder: "e.g., Mumbai Office / Remote / Hybrid",
    group: "Role Details",
  },
  {
    name: "ctc_annual",
    label: "Annual CTC (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 1200000",
    group: "Compensation",
  },
  {
    name: "basic_salary_monthly",
    label: "Monthly Basic Salary (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 40000",
    helpText: "Usually 40-50% of monthly CTC",
    group: "Compensation",
  },
  {
    name: "hra_monthly",
    label: "Monthly HRA (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 20000",
    group: "Compensation",
  },
  {
    name: "variable_pay",
    label: "Annual Variable / Bonus (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 100000",
    helpText: "Leave blank if no variable component",
    group: "Compensation",
  },
  {
    name: "pf_applicable",
    label: "Is PF Applicable?",
    type: "select",
    required: true,
    options: [
      { value: "yes", label: "Yes — employer contributes to EPF" },
      { value: "no", label: "No — not applicable" },
    ],
    helpText: "Mandatory if company has 20+ employees",
    group: "Compensation",
  },
  {
    name: "joining_date",
    label: "Joining Date",
    type: "date",
    required: true,
    group: "Employment Terms",
  },
  {
    name: "probation_months",
    label: "Probation Period (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 3",
    default: 3,
    validation: { min: 0, max: 12 },
    group: "Employment Terms",
  },
  {
    name: "notice_period_months",
    label: "Notice Period (Months) — Equal for Both",
    type: "number",
    required: true,
    placeholder: "e.g., 2",
    default: 2,
    helpText: "Same notice period for employer and employee",
    validation: { min: 1, max: 6 },
    group: "Employment Terms",
  },
  {
    name: "working_hours",
    label: "Working Hours Per Day",
    type: "number",
    required: false,
    placeholder: "e.g., 8",
    default: 8,
    validation: { min: 4, max: 12 },
    group: "Employment Terms",
  },
  {
    name: "leaves_per_year",
    label: "Total Paid Leaves Per Year",
    type: "number",
    required: false,
    placeholder: "e.g., 24",
    default: 24,
    validation: { min: 12, max: 60 },
    group: "Employment Terms",
  },
  {
    name: "has_training_bond",
    label: "Is There a Training Bond?",
    type: "select",
    required: true,
    options: [
      { value: "no", label: "No training bond" },
      { value: "yes", label: "Yes — training bond applies" },
    ],
    group: "Employment Terms",
  },
  {
    name: "training_bond_months",
    label: "Training Bond Duration (Months)",
    type: "number",
    required: false,
    placeholder: "e.g., 12",
    helpText: "Only if training bond is applicable",
    validation: { min: 1, max: 36 },
    group: "Employment Terms",
  },
  {
    name: "training_bond_amount",
    label: "Training Bond Amount (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 100000",
    helpText: "Must not exceed actual training cost",
    group: "Employment Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., WFH policy, relocation allowance, ESOP...",
    group: "Additional",
  },
];

// ============================================
// NDA FIELDS
// ============================================

const ndaFields: TemplateField[] = [
  {
    name: "party_a_name",
    label: "Disclosing Party Name",
    type: "text",
    required: true,
    placeholder: "e.g., Acme Technologies Pvt. Ltd.",
    group: "Party A (Disclosing Party)",
  },
  {
    name: "party_a_address",
    label: "Disclosing Party Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Party A (Disclosing Party)",
  },
  {
    name: "party_a_type",
    label: "Disclosing Party Type",
    type: "select",
    required: true,
    options: [
      { value: "company", label: "Company / Organization" },
      { value: "individual", label: "Individual" },
      { value: "partnership", label: "Partnership Firm" },
      { value: "llp", label: "LLP" },
    ],
    group: "Party A (Disclosing Party)",
  },
  {
    name: "party_b_name",
    label: "Receiving Party Name",
    type: "text",
    required: true,
    placeholder: "e.g., John Doe / XYZ Consulting",
    group: "Party B (Receiving Party)",
  },
  {
    name: "party_b_address",
    label: "Receiving Party Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Party B (Receiving Party)",
  },
  {
    name: "party_b_type",
    label: "Receiving Party Type",
    type: "select",
    required: true,
    options: [
      { value: "company", label: "Company / Organization" },
      { value: "individual", label: "Individual" },
      { value: "partnership", label: "Partnership Firm" },
      { value: "llp", label: "LLP" },
    ],
    group: "Party B (Receiving Party)",
  },
  {
    name: "is_mutual",
    label: "Is This a Mutual NDA?",
    type: "select",
    required: true,
    options: [
      { value: "yes", label: "Yes — both parties share confidential info" },
      { value: "no", label: "No — one-way disclosure only" },
    ],
    helpText: "Mutual NDAs are fairer and recommended",
    group: "NDA Terms",
  },
  {
    name: "purpose",
    label: "Purpose of Disclosure",
    type: "textarea",
    required: true,
    placeholder: "e.g., Evaluating potential business partnership for software development project",
    group: "NDA Terms",
  },
  {
    name: "effective_date",
    label: "Effective Date",
    type: "date",
    required: true,
    group: "NDA Terms",
  },
  {
    name: "duration_years",
    label: "Confidentiality Duration (Years)",
    type: "number",
    required: true,
    placeholder: "e.g., 2",
    default: 2,
    helpText: "1-3 years is standard. Max 5 years recommended",
    validation: { min: 1, max: 5 },
    group: "NDA Terms",
  },
  {
    name: "scope_description",
    label: "What Information is Confidential?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Business plans, source code, customer data, financial information...",
    helpText: "Be specific — overly broad NDAs are weaker legally",
    group: "NDA Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Specific exclusions, return of materials timeline...",
    group: "Additional",
  },
];

// ============================================
// FREELANCE CONTRACT FIELDS
// ============================================

const freelanceFields: TemplateField[] = [
  {
    name: "client_name",
    label: "Client Name",
    type: "text",
    required: true,
    placeholder: "e.g., Bright Ideas Marketing Pvt. Ltd.",
    group: "Client Details",
  },
  {
    name: "client_address",
    label: "Client Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Client Details",
  },
  {
    name: "freelancer_name",
    label: "Freelancer / Contractor Name",
    type: "text",
    required: true,
    placeholder: "e.g., Riya Desai",
    group: "Freelancer Details",
  },
  {
    name: "freelancer_address",
    label: "Freelancer Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Freelancer Details",
  },
  {
    name: "freelancer_pan",
    label: "Freelancer PAN (Optional)",
    type: "text",
    required: false,
    placeholder: "e.g., ABCDE1234F",
    helpText: "Required for TDS purposes if payment > ₹30,000",
    group: "Freelancer Details",
  },
  {
    name: "project_title",
    label: "Project Title",
    type: "text",
    required: true,
    placeholder: "e.g., Website Redesign for BrightIdeas.com",
    group: "Project Details",
  },
  {
    name: "project_description",
    label: "Project Description & Scope",
    type: "textarea",
    required: true,
    placeholder: "Detailed description of what will be delivered...",
    group: "Project Details",
  },
  {
    name: "deliverables",
    label: "Specific Deliverables",
    type: "textarea",
    required: true,
    placeholder: "e.g., 1. Homepage design, 2. 5 inner pages, 3. Mobile responsive, 4. Source files",
    group: "Project Details",
  },
  {
    name: "project_start_date",
    label: "Project Start Date",
    type: "date",
    required: true,
    group: "Project Details",
  },
  {
    name: "project_end_date",
    label: "Expected Completion Date",
    type: "date",
    required: true,
    group: "Project Details",
  },
  {
    name: "revision_rounds",
    label: "Included Revision Rounds",
    type: "number",
    required: true,
    placeholder: "e.g., 2",
    default: 2,
    helpText: "Additional revisions will be charged extra",
    validation: { min: 0, max: 10 },
    group: "Project Details",
  },
  {
    name: "total_fee",
    label: "Total Project Fee (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 75000",
    group: "Payment Terms",
  },
  {
    name: "payment_schedule",
    label: "Payment Schedule",
    type: "select",
    required: true,
    options: [
      { value: "milestone", label: "Milestone-based payments" },
      { value: "50_50", label: "50% advance + 50% on completion" },
      { value: "40_30_30", label: "40% advance + 30% mid + 30% completion" },
      { value: "monthly", label: "Monthly payments" },
      { value: "on_completion", label: "Full payment on completion" },
    ],
    helpText: "Advance payment protects the freelancer",
    group: "Payment Terms",
  },
  {
    name: "payment_due_days",
    label: "Payment Due Within (Days) After Invoice",
    type: "number",
    required: false,
    placeholder: "e.g., 15",
    default: 15,
    validation: { min: 7, max: 60 },
    group: "Payment Terms",
  },
  {
    name: "ip_ownership",
    label: "Intellectual Property Ownership",
    type: "select",
    required: true,
    options: [
      { value: "client_on_payment", label: "Transfers to client upon FULL payment" },
      { value: "freelancer", label: "Remains with freelancer (client gets license)" },
      { value: "shared", label: "Shared ownership" },
    ],
    helpText: "IP transfer upon full payment is fairest",
    group: "Terms",
  },
  {
    name: "confidentiality",
    label: "Include Confidentiality Clause?",
    type: "select",
    required: false,
    options: [
      { value: "yes", label: "Yes — mutual confidentiality" },
      { value: "no", label: "No" },
    ],
    default: "yes",
    group: "Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Tools provided by client, communication channels...",
    group: "Additional",
  },
];

// ============================================
// LOAN AGREEMENT FIELDS
// ============================================

const loanFields: TemplateField[] = [
  {
    name: "lender_name",
    label: "Lender Full Name / Organization",
    type: "text",
    required: true,
    placeholder: "e.g., Suresh Babu Reddy / ABC Finance Ltd.",
    group: "Lender Details",
  },
  {
    name: "lender_address",
    label: "Lender Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Lender Details",
  },
  {
    name: "lender_pan",
    label: "Lender PAN",
    type: "text",
    required: false,
    placeholder: "e.g., ABCDE1234F",
    group: "Lender Details",
  },
  {
    name: "lender_type",
    label: "Lender Type",
    type: "select",
    required: true,
    options: [
      { value: "individual", label: "Individual" },
      { value: "nbfc", label: "NBFC (Non-Banking Financial Company)" },
      { value: "company", label: "Company / Corporate" },
      { value: "partnership", label: "Partnership Firm" },
    ],
    group: "Lender Details",
  },
  {
    name: "borrower_name",
    label: "Borrower Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Amit Sharma",
    group: "Borrower Details",
  },
  {
    name: "borrower_address",
    label: "Borrower Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Borrower Details",
  },
  {
    name: "borrower_pan",
    label: "Borrower PAN",
    type: "text",
    required: false,
    placeholder: "e.g., FGHIJ5678K",
    group: "Borrower Details",
  },
  {
    name: "loan_amount",
    label: "Loan Amount (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 500000",
    group: "Loan Terms",
  },
  {
    name: "loan_purpose",
    label: "Purpose of Loan",
    type: "select",
    required: true,
    options: [
      { value: "personal", label: "Personal Use" },
      { value: "business", label: "Business / Working Capital" },
      { value: "education", label: "Education" },
      { value: "medical", label: "Medical" },
      { value: "home_improvement", label: "Home Improvement" },
      { value: "vehicle", label: "Vehicle Purchase" },
      { value: "other", label: "Other" },
    ],
    group: "Loan Terms",
  },
  {
    name: "interest_rate_annual",
    label: "Annual Interest Rate (%)",
    type: "number",
    required: true,
    placeholder: "e.g., 12",
    helpText: "Must be reasonable. RBI usury guidelines apply",
    validation: { min: 0, max: 36 },
    group: "Loan Terms",
  },
  {
    name: "interest_type",
    label: "Interest Calculation Method",
    type: "select",
    required: true,
    options: [
      { value: "simple", label: "Simple Interest" },
      { value: "reducing_balance", label: "Reducing Balance (EMI)" },
      { value: "compound_monthly", label: "Compound — Monthly" },
      { value: "compound_quarterly", label: "Compound — Quarterly" },
    ],
    helpText: "Reducing balance is fairest for EMI-based loans",
    group: "Loan Terms",
  },
  {
    name: "tenure_months",
    label: "Loan Tenure (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 24",
    validation: { min: 1, max: 360 },
    group: "Loan Terms",
  },
  {
    name: "disbursement_date",
    label: "Disbursement Date",
    type: "date",
    required: true,
    group: "Loan Terms",
  },
  {
    name: "repayment_frequency",
    label: "Repayment Frequency",
    type: "select",
    required: true,
    options: [
      { value: "monthly", label: "Monthly EMI" },
      { value: "quarterly", label: "Quarterly" },
      { value: "lump_sum", label: "Lump Sum at Maturity" },
      { value: "bullet", label: "Interest Monthly + Principal at End" },
    ],
    group: "Loan Terms",
  },
  {
    name: "processing_fee",
    label: "Processing Fee (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 5000",
    helpText: "Leave blank if no processing fee",
    group: "Fees & Charges",
  },
  {
    name: "prepayment_allowed",
    label: "Is Prepayment / Foreclosure Allowed?",
    type: "select",
    required: true,
    options: [
      { value: "yes_no_penalty", label: "Yes — no penalty" },
      { value: "yes_with_penalty", label: "Yes — with reasonable penalty" },
      { value: "after_lockin", label: "Yes — after lock-in period only" },
    ],
    helpText: "RBI recommends no prepayment penalty on floating rate loans",
    group: "Fees & Charges",
  },
  {
    name: "prepayment_penalty_percent",
    label: "Prepayment Penalty (%)",
    type: "number",
    required: false,
    placeholder: "e.g., 2",
    helpText: "Only if prepayment has penalty. Max 2-4% is standard",
    validation: { min: 0, max: 5 },
    group: "Fees & Charges",
  },
  {
    name: "late_payment_penalty",
    label: "Late Payment Penalty (% per month)",
    type: "number",
    required: false,
    placeholder: "e.g., 2",
    helpText: "Must be reasonable per Section 74, Indian Contract Act",
    validation: { min: 0, max: 5 },
    group: "Fees & Charges",
  },
  {
    name: "collateral_type",
    label: "Collateral / Security",
    type: "select",
    required: true,
    options: [
      { value: "unsecured", label: "Unsecured (No collateral)" },
      { value: "property", label: "Immovable Property" },
      { value: "vehicle", label: "Vehicle" },
      { value: "gold", label: "Gold / Jewellery" },
      { value: "fd", label: "Fixed Deposit" },
      { value: "shares", label: "Shares / Securities" },
      { value: "other", label: "Other Asset" },
    ],
    group: "Security",
  },
  {
    name: "collateral_description",
    label: "Collateral Description (if secured)",
    type: "textarea",
    required: false,
    placeholder: "e.g., Flat No 201, Building XYZ, Survey No 45, Mumbai...",
    helpText: "Detailed description of the collateral asset",
    group: "Security",
  },
  {
    name: "guarantor_name",
    label: "Guarantor Name (if any)",
    type: "text",
    required: false,
    placeholder: "e.g., Vijay Kumar",
    helpText: "Leave blank if no guarantor",
    group: "Security",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Moratorium period, insurance requirement...",
    group: "Additional",
  },
];

// ============================================
// PARTNERSHIP DEED FIELDS
// ============================================

const partnershipFields: TemplateField[] = [
  {
    name: "firm_name",
    label: "Partnership Firm Name",
    type: "text",
    required: true,
    placeholder: "e.g., Sharma & Associates",
    group: "Firm Details",
  },
  {
    name: "business_nature",
    label: "Nature of Business",
    type: "text",
    required: true,
    placeholder: "e.g., Software Development and IT Consulting",
    group: "Firm Details",
  },
  {
    name: "business_address",
    label: "Principal Place of Business",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Firm Details",
  },
  {
    name: "commencement_date",
    label: "Date of Commencement",
    type: "date",
    required: true,
    group: "Firm Details",
  },
  {
    name: "firm_duration",
    label: "Firm Duration",
    type: "select",
    required: true,
    options: [
      { value: "at_will", label: "At Will (no fixed duration)" },
      { value: "fixed", label: "Fixed Duration" },
    ],
    group: "Firm Details",
  },
  {
    name: "firm_duration_years",
    label: "Duration (Years) — if fixed",
    type: "number",
    required: false,
    placeholder: "e.g., 10",
    validation: { min: 1, max: 50 },
    group: "Firm Details",
  },
  {
    name: "partner_1_name",
    label: "Partner 1 — Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Rahul Sharma",
    group: "Partner 1",
  },
  {
    name: "partner_1_address",
    label: "Partner 1 — Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Partner 1",
  },
  {
    name: "partner_1_pan",
    label: "Partner 1 — PAN",
    type: "text",
    required: false,
    placeholder: "e.g., ABCDE1234F",
    group: "Partner 1",
  },
  {
    name: "partner_1_capital",
    label: "Partner 1 — Capital Contribution (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 500000",
    group: "Partner 1",
  },
  {
    name: "partner_1_profit_share",
    label: "Partner 1 — Profit Share (%)",
    type: "number",
    required: true,
    placeholder: "e.g., 50",
    validation: { min: 1, max: 99 },
    group: "Partner 1",
  },
  {
    name: "partner_2_name",
    label: "Partner 2 — Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Neha Gupta",
    group: "Partner 2",
  },
  {
    name: "partner_2_address",
    label: "Partner 2 — Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Partner 2",
  },
  {
    name: "partner_2_pan",
    label: "Partner 2 — PAN",
    type: "text",
    required: false,
    placeholder: "e.g., FGHIJ5678K",
    group: "Partner 2",
  },
  {
    name: "partner_2_capital",
    label: "Partner 2 — Capital Contribution (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 500000",
    group: "Partner 2",
  },
  {
    name: "partner_2_profit_share",
    label: "Partner 2 — Profit Share (%)",
    type: "number",
    required: true,
    placeholder: "e.g., 50",
    validation: { min: 1, max: 99 },
    group: "Partner 2",
  },
  {
    name: "interest_on_capital",
    label: "Interest on Capital (% per annum)",
    type: "number",
    required: false,
    placeholder: "e.g., 6",
    default: 6,
    helpText: "Standard is 6% per annum as per Income Tax Act",
    validation: { min: 0, max: 12 },
    group: "Financial Terms",
  },
  {
    name: "partner_salary_monthly",
    label: "Monthly Salary to Working Partners (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 30000",
    helpText: "Leave blank if no salary to partners",
    group: "Financial Terms",
  },
  {
    name: "drawing_limit_monthly",
    label: "Monthly Drawing Limit per Partner (₹)",
    type: "currency",
    required: false,
    placeholder: "e.g., 50000",
    helpText: "Max amount a partner can withdraw monthly",
    group: "Financial Terms",
  },
  {
    name: "bank_account_operator",
    label: "Who Can Operate Bank Account?",
    type: "select",
    required: true,
    options: [
      { value: "any_partner", label: "Any partner individually" },
      { value: "jointly", label: "All partners jointly" },
      { value: "specific", label: "Specific partner(s) only" },
    ],
    group: "Financial Terms",
  },
  {
    name: "new_partner_admission",
    label: "New Partner Admission Requires",
    type: "select",
    required: true,
    options: [
      { value: "unanimous", label: "Unanimous consent of all partners" },
      { value: "majority", label: "Majority consent" },
    ],
    group: "Governance",
  },
  {
    name: "retirement_notice_months",
    label: "Retirement Notice Period (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 3",
    default: 3,
    validation: { min: 1, max: 12 },
    group: "Governance",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Non-compete during partnership, specific responsibilities...",
    group: "Additional",
  },
];

// ============================================
// SALE AGREEMENT FIELDS
// ============================================

const saleFields: TemplateField[] = [
  {
    name: "seller_name",
    label: "Seller Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Mohan Lal Agarwal",
    group: "Seller Details",
  },
  {
    name: "seller_address",
    label: "Seller Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Seller Details",
  },
  {
    name: "seller_pan",
    label: "Seller PAN",
    type: "text",
    required: false,
    placeholder: "e.g., ABCDE1234F",
    group: "Seller Details",
  },
  {
    name: "buyer_name",
    label: "Buyer Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Kavita Joshi",
    group: "Buyer Details",
  },
  {
    name: "buyer_address",
    label: "Buyer Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Buyer Details",
  },
  {
    name: "buyer_pan",
    label: "Buyer PAN",
    type: "text",
    required: false,
    placeholder: "e.g., FGHIJ5678K",
    group: "Buyer Details",
  },
  {
    name: "sale_type",
    label: "Type of Sale",
    type: "select",
    required: true,
    options: [
      { value: "residential_flat", label: "Residential Flat / Apartment" },
      { value: "residential_house", label: "Independent House / Villa" },
      { value: "residential_plot", label: "Residential Plot / Land" },
      { value: "commercial_property", label: "Commercial Property" },
      { value: "agricultural_land", label: "Agricultural Land" },
      { value: "vehicle", label: "Vehicle" },
      { value: "business", label: "Business / Going Concern" },
      { value: "goods", label: "Goods / Movable Property" },
    ],
    group: "Property Details",
  },
  {
    name: "property_description",
    label: "Property / Asset Description",
    type: "textarea",
    required: true,
    placeholder: "Full description — address, survey no, area, floor, boundaries, vehicle reg no, etc.",
    group: "Property Details",
  },
  {
    name: "property_area",
    label: "Area (sq ft / sq meters / acres)",
    type: "text",
    required: false,
    placeholder: "e.g., 1200 sq ft carpet area",
    helpText: "Use carpet area for flats (RERA requirement)",
    group: "Property Details",
  },
  {
    name: "rera_registration",
    label: "RERA Registration Number (if applicable)",
    type: "text",
    required: false,
    placeholder: "e.g., P52100012345",
    helpText: "Required for under-construction properties",
    group: "Property Details",
  },
  {
    name: "total_sale_price",
    label: "Total Sale Price (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 7500000",
    group: "Financial Terms",
  },
  {
    name: "token_advance",
    label: "Token / Advance Amount (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 200000",
    helpText: "Amount paid at signing of this agreement",
    group: "Financial Terms",
  },
  {
    name: "payment_schedule",
    label: "Payment Schedule",
    type: "select",
    required: true,
    options: [
      { value: "full_at_registration", label: "Balance at registration" },
      { value: "installments", label: "Installments before registration" },
      { value: "construction_linked", label: "Construction-linked (for under-construction)" },
      { value: "on_delivery", label: "Full payment on delivery" },
    ],
    group: "Financial Terms",
  },
  {
    name: "stamp_duty_bearer",
    label: "Who Bears Stamp Duty & Registration Charges?",
    type: "select",
    required: true,
    options: [
      { value: "buyer", label: "Buyer (standard practice)" },
      { value: "seller", label: "Seller" },
      { value: "shared", label: "Shared equally" },
    ],
    group: "Financial Terms",
  },
  {
    name: "possession_date",
    label: "Expected Possession / Handover Date",
    type: "date",
    required: true,
    group: "Timeline",
  },
  {
    name: "registration_deadline",
    label: "Registration Deadline Date",
    type: "date",
    required: false,
    helpText: "Date by which sale deed must be registered",
    group: "Timeline",
  },
  {
    name: "encumbrance_free",
    label: "Is Property Free from Encumbrances?",
    type: "select",
    required: true,
    options: [
      { value: "yes", label: "Yes — clear title, no loans/liens" },
      { value: "loan_pending", label: "Existing loan — will be cleared before sale" },
      { value: "partial", label: "Partial encumbrance — details in additional terms" },
    ],
    group: "Title & Encumbrance",
  },
  {
    name: "title_documents",
    label: "Title Documents Available",
    type: "textarea",
    required: false,
    placeholder: "e.g., Original sale deed, society NOC, latest tax receipts, EC for 30 years...",
    group: "Title & Encumbrance",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Fixtures included, parking slot, society transfer charges...",
    group: "Additional",
  },
];

// ============================================
// SERVICE / CONSULTANCY AGREEMENT FIELDS
// ============================================

const serviceFields: TemplateField[] = [
  {
    name: "provider_name",
    label: "Service Provider Name",
    type: "text",
    required: true,
    placeholder: "e.g., NextGen Consulting LLP",
    group: "Service Provider",
  },
  {
    name: "provider_address",
    label: "Service Provider Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Service Provider",
  },
  {
    name: "provider_type",
    label: "Provider Type",
    type: "select",
    required: true,
    options: [
      { value: "individual", label: "Individual Consultant" },
      { value: "company", label: "Company" },
      { value: "llp", label: "LLP" },
      { value: "partnership", label: "Partnership Firm" },
      { value: "proprietorship", label: "Proprietorship" },
    ],
    group: "Service Provider",
  },
  {
    name: "provider_gstin",
    label: "Provider GSTIN (if applicable)",
    type: "text",
    required: false,
    placeholder: "e.g., 27AABCU9603R1ZM",
    group: "Service Provider",
  },
  {
    name: "client_name",
    label: "Client Name",
    type: "text",
    required: true,
    placeholder: "e.g., TechVista Pvt. Ltd.",
    group: "Client Details",
  },
  {
    name: "client_address",
    label: "Client Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Client Details",
  },
  {
    name: "service_description",
    label: "Description of Services",
    type: "textarea",
    required: true,
    placeholder: "Detailed description of services to be provided...",
    group: "Service Details",
  },
  {
    name: "deliverables",
    label: "Key Deliverables",
    type: "textarea",
    required: true,
    placeholder: "e.g., 1. Monthly reports, 2. Strategy document, 3. Training sessions...",
    group: "Service Details",
  },
  {
    name: "start_date",
    label: "Service Start Date",
    type: "date",
    required: true,
    group: "Service Details",
  },
  {
    name: "end_date",
    label: "Service End Date",
    type: "date",
    required: true,
    group: "Service Details",
  },
  {
    name: "engagement_type",
    label: "Engagement Type",
    type: "select",
    required: true,
    options: [
      { value: "retainer", label: "Monthly Retainer" },
      { value: "project", label: "Fixed Project Fee" },
      { value: "hourly", label: "Hourly / Time-based" },
      { value: "milestone", label: "Milestone-based" },
    ],
    group: "Service Details",
  },
  {
    name: "total_fee",
    label: "Total Fee / Monthly Retainer (₹)",
    type: "currency",
    required: true,
    placeholder: "e.g., 150000",
    group: "Payment Terms",
  },
  {
    name: "payment_frequency",
    label: "Payment Frequency",
    type: "select",
    required: true,
    options: [
      { value: "monthly", label: "Monthly" },
      { value: "quarterly", label: "Quarterly" },
      { value: "milestone", label: "On milestone completion" },
      { value: "on_completion", label: "On project completion" },
      { value: "advance", label: "Full advance" },
    ],
    group: "Payment Terms",
  },
  {
    name: "payment_due_days",
    label: "Payment Due Within (Days) After Invoice",
    type: "number",
    required: false,
    placeholder: "e.g., 15",
    default: 15,
    validation: { min: 7, max: 60 },
    group: "Payment Terms",
  },
  {
    name: "notice_period_days",
    label: "Termination Notice Period (Days)",
    type: "number",
    required: true,
    placeholder: "e.g., 30",
    default: 30,
    helpText: "Equal for both parties",
    validation: { min: 7, max: 90 },
    group: "Terms",
  },
  {
    name: "confidentiality",
    label: "Include Confidentiality Clause?",
    type: "select",
    required: true,
    options: [
      { value: "mutual", label: "Yes — mutual confidentiality" },
      { value: "one_way", label: "Yes — client info only" },
      { value: "no", label: "No" },
    ],
    group: "Terms",
  },
  {
    name: "ip_ownership",
    label: "Work Product IP Ownership",
    type: "select",
    required: true,
    options: [
      { value: "client_on_payment", label: "Client — upon full payment" },
      { value: "provider", label: "Service provider retains" },
      { value: "shared", label: "Shared / Licensed" },
    ],
    group: "Terms",
  },
  {
    name: "liability_cap",
    label: "Liability Cap",
    type: "select",
    required: false,
    options: [
      { value: "contract_value", label: "Capped at total contract value" },
      { value: "6_months", label: "Capped at 6 months fees" },
      { value: "unlimited", label: "Unlimited (not recommended)" },
    ],
    default: "contract_value",
    group: "Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., On-site days, reporting frequency, expense reimbursement...",
    group: "Additional",
  },
];

// ============================================
// MOU (MEMORANDUM OF UNDERSTANDING) FIELDS
// ============================================

const mouFields: TemplateField[] = [
  {
    name: "party_a_name",
    label: "Party A — Name",
    type: "text",
    required: true,
    placeholder: "e.g., Innovate Labs Pvt. Ltd.",
    group: "Party A",
  },
  {
    name: "party_a_address",
    label: "Party A — Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Party A",
  },
  {
    name: "party_a_representative",
    label: "Party A — Authorized Representative",
    type: "text",
    required: true,
    placeholder: "e.g., Vikram Singh, Director",
    group: "Party A",
  },
  {
    name: "party_b_name",
    label: "Party B — Name",
    type: "text",
    required: true,
    placeholder: "e.g., Green Energy Solutions",
    group: "Party B",
  },
  {
    name: "party_b_address",
    label: "Party B — Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Party B",
  },
  {
    name: "party_b_representative",
    label: "Party B — Authorized Representative",
    type: "text",
    required: true,
    placeholder: "e.g., Anita Kapoor, Managing Partner",
    group: "Party B",
  },
  {
    name: "mou_purpose",
    label: "Purpose of MOU",
    type: "textarea",
    required: true,
    placeholder: "e.g., To explore a joint venture for solar panel manufacturing and distribution in Maharashtra",
    group: "MOU Terms",
  },
  {
    name: "effective_date",
    label: "Effective Date",
    type: "date",
    required: true,
    group: "MOU Terms",
  },
  {
    name: "mou_duration_months",
    label: "MOU Validity (Months)",
    type: "number",
    required: true,
    placeholder: "e.g., 6",
    default: 6,
    helpText: "Period to finalize formal agreement. 3-12 months typical",
    validation: { min: 1, max: 24 },
    group: "MOU Terms",
  },
  {
    name: "is_binding",
    label: "Is This MOU Legally Binding?",
    type: "select",
    required: true,
    options: [
      { value: "non_binding", label: "Non-binding (except confidentiality)" },
      { value: "partially_binding", label: "Partially binding — some clauses binding" },
      { value: "fully_binding", label: "Fully binding" },
    ],
    helpText: "Non-binding is standard for MOUs. Confidentiality is usually always binding",
    group: "MOU Terms",
  },
  {
    name: "exclusivity",
    label: "Exclusivity",
    type: "select",
    required: true,
    options: [
      { value: "exclusive", label: "Exclusive — parties won't negotiate with others" },
      { value: "non_exclusive", label: "Non-exclusive — parties free to explore others" },
    ],
    group: "MOU Terms",
  },
  {
    name: "party_a_responsibilities",
    label: "Party A — Key Responsibilities",
    type: "textarea",
    required: false,
    placeholder: "e.g., Provide technical expertise, fund R&D phase...",
    group: "Responsibilities",
  },
  {
    name: "party_b_responsibilities",
    label: "Party B — Key Responsibilities",
    type: "textarea",
    required: false,
    placeholder: "e.g., Provide market access, handle distribution...",
    group: "Responsibilities",
  },
  {
    name: "financial_terms",
    label: "Preliminary Financial Terms (if any)",
    type: "textarea",
    required: false,
    placeholder: "e.g., 50-50 cost sharing during MOU period, each party bears own expenses...",
    group: "Responsibilities",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Conditions for converting to formal agreement...",
    group: "Additional",
  },
];

// ============================================
// POWER OF ATTORNEY FIELDS
// ============================================

const poaFields: TemplateField[] = [
  {
    name: "principal_name",
    label: "Principal (Grantor) Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Rajendra Prasad Gupta",
    helpText: "Person granting the power",
    group: "Principal (Grantor)",
  },
  {
    name: "principal_address",
    label: "Principal Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Principal (Grantor)",
  },
  {
    name: "principal_aadhaar_last4",
    label: "Principal Aadhaar (Last 4)",
    type: "text",
    required: false,
    placeholder: "e.g., 9876",
    group: "Principal (Grantor)",
  },
  {
    name: "principal_is_nri",
    label: "Is Principal an NRI / Overseas?",
    type: "select",
    required: true,
    options: [
      { value: "no", label: "No — resides in India" },
      { value: "yes", label: "Yes — NRI / residing abroad" },
    ],
    helpText: "NRI POAs need consulate attestation",
    group: "Principal (Grantor)",
  },
  {
    name: "agent_name",
    label: "Agent (Attorney) Full Name",
    type: "text",
    required: true,
    placeholder: "e.g., Sunita Gupta",
    helpText: "Person receiving the power to act",
    group: "Agent (Attorney)",
  },
  {
    name: "agent_address",
    label: "Agent Address",
    type: "textarea",
    required: true,
    placeholder: "Full address with PIN code",
    group: "Agent (Attorney)",
  },
  {
    name: "agent_relationship",
    label: "Relationship to Principal",
    type: "text",
    required: false,
    placeholder: "e.g., Wife, Son, Brother, Business Partner",
    group: "Agent (Attorney)",
  },
  {
    name: "poa_type",
    label: "Type of Power of Attorney",
    type: "select",
    required: true,
    options: [
      { value: "general", label: "General POA — broad powers for all affairs" },
      { value: "special", label: "Special POA — specific act/transaction only" },
    ],
    helpText: "Special POA is recommended — more secure and specific",
    group: "POA Terms",
  },
  {
    name: "poa_purpose",
    label: "Purpose / Powers Being Granted",
    type: "textarea",
    required: true,
    placeholder: "e.g., To sell flat No 301, Building ABC, Mumbai on my behalf and sign all documents...",
    group: "POA Terms",
  },
  {
    name: "property_details",
    label: "Property Details (if property-related)",
    type: "textarea",
    required: false,
    placeholder: "Full property description — address, survey no, area, registration details...",
    helpText: "Required for property-related POA",
    group: "POA Terms",
  },
  {
    name: "effective_date",
    label: "Effective Date",
    type: "date",
    required: true,
    group: "POA Terms",
  },
  {
    name: "validity_duration",
    label: "Validity Duration",
    type: "select",
    required: true,
    options: [
      { value: "until_revoked", label: "Until revoked by principal" },
      { value: "6_months", label: "6 months" },
      { value: "1_year", label: "1 year" },
      { value: "2_years", label: "2 years" },
      { value: "specific_transaction", label: "Until specific transaction is completed" },
    ],
    helpText: "Limited duration is safer",
    group: "POA Terms",
  },
  {
    name: "is_revocable",
    label: "Is This POA Revocable?",
    type: "select",
    required: true,
    options: [
      { value: "revocable", label: "Yes — can be revoked anytime" },
      { value: "irrevocable", label: "No — irrevocable (coupled with interest)" },
    ],
    helpText: "Revocable is standard and recommended. Irrevocable only in special cases",
    group: "POA Terms",
  },
  {
    name: "can_sub_delegate",
    label: "Can Agent Sub-delegate Powers?",
    type: "select",
    required: true,
    options: [
      { value: "no", label: "No — agent must act personally" },
      { value: "yes", label: "Yes — can appoint sub-agent" },
    ],
    group: "POA Terms",
  },
  {
    name: "additional_terms",
    label: "Any Additional Terms / Restrictions?",
    type: "textarea",
    required: false,
    placeholder: "e.g., Cannot sell below ₹X amount, must consult before signing, reporting requirements...",
    group: "Additional",
  },
];

// ============================================
// TEMPLATE CONFIGS — ALL TEMPLATES
// ============================================

export const TEMPLATE_CONFIGS: Record<ContractTemplateType, TemplateConfig> = {
  rental: {
    type: "rental",
    name: "Rental / Leave & License Agreement",
    description:
      "Fair rental agreement compliant with Model Tenancy Act, Transfer of Property Act, and state-specific Rent Control Acts. Protects both landlord and tenant equally.",
    icon: "Home",
    fields: rentalFields,
    applicableLaws: [
      { name: "Model Tenancy Act", section: "2021", relevance: "Deposit limits, notice periods" },
      { name: "Transfer of Property Act", section: "1882, Sec 106-108", relevance: "Lease rights & obligations" },
      { name: "Indian Contract Act", section: "1872", relevance: "Validity of agreement" },
      { name: "Registration Act", section: "1908", relevance: "Registration if > 12 months" },
      { name: "Indian Stamp Act", section: "1899", relevance: "Stamp duty requirements" },
    ],
  },
  employment: {
    type: "employment",
    name: "Employment Contract / Offer Letter",
    description:
      "Fair employment contract with equal notice periods, legal PF/ESI compliance, and no void non-compete clauses. Protects employer and employee.",
    icon: "Briefcase",
    fields: employmentFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872, Sec 27", relevance: "Non-compete void post-employment" },
      { name: "Payment of Wages Act", section: "1936", relevance: "Salary payment rules" },
      { name: "EPF & MP Act", section: "1952", relevance: "Provident fund mandatory" },
      { name: "Payment of Gratuity Act", section: "1972", relevance: "Gratuity after 5 years" },
      { name: "Shops & Establishments Act", section: "State-specific", relevance: "Working hours, leaves" },
    ],
  },
  nda: {
    type: "nda",
    name: "Non-Disclosure Agreement (NDA)",
    description:
      "Balanced NDA with reasonable scope and duration, standard exclusions, and mutual obligations where possible. Enforceable under Indian law.",
    icon: "ShieldCheck",
    fields: ndaFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872, Sec 27", relevance: "Reasonable restraint only" },
      { name: "IT Act", section: "2000, Sec 72A", relevance: "Breach of confidentiality" },
      { name: "Copyright Act", section: "1957", relevance: "IP protection" },
      { name: "Indian Evidence Act", section: "1872", relevance: "Burden of proof" },
    ],
  },
  freelance: {
    type: "freelance",
    name: "Freelance / Independent Contractor Agreement",
    description:
      "Fair freelance contract with clear deliverables, milestone payments, IP protection, and kill fee. Protects both client and freelancer.",
    icon: "Handshake",
    fields: freelanceFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872", relevance: "Contract validity" },
      { name: "Copyright Act", section: "1957, Sec 17-18", relevance: "Work-for-hire IP" },
      { name: "Income Tax Act", section: "1961, Sec 194C", relevance: "TDS on contractor payments" },
      { name: "GST Act", section: "2017", relevance: "GST if turnover > ₹20L" },
    ],
  },
  loan: {
    type: "loan",
    name: "Loan Agreement",
    description:
      "Fair loan agreement with transparent interest rates, no hidden charges, reasonable prepayment terms, and RBI-compliant clauses. Protects lender and borrower.",
    icon: "Wallet",
    fields: loanFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872, Sec 74", relevance: "Reasonable penalty only" },
      { name: "RBI Fair Practices Code", section: "2003/2012", relevance: "Lending norms" },
      { name: "Negotiable Instruments Act", section: "1881", relevance: "Promissory notes, cheques" },
      { name: "Transfer of Property Act", section: "1882, Sec 58-104", relevance: "Mortgage provisions" },
      { name: "SARFAESI Act", section: "2002", relevance: "Secured asset recovery (NBFC/banks)" },
    ],
  },
  partnership: {
    type: "partnership",
    name: "Partnership Deed",
    description:
      "Fair partnership deed with clear profit sharing, capital terms, governance rules, and exit provisions. Compliant with Indian Partnership Act, 1932.",
    icon: "Users",
    fields: partnershipFields,
    applicableLaws: [
      { name: "Indian Partnership Act", section: "1932", relevance: "Partnership formation & governance" },
      { name: "Indian Contract Act", section: "1872", relevance: "Agreement validity" },
      { name: "Income Tax Act", section: "1961, Sec 184-185", relevance: "Partnership taxation" },
      { name: "Registration Act", section: "1908", relevance: "Optional registration benefits" },
      { name: "Indian Stamp Act", section: "1899", relevance: "Stamp duty on deed" },
    ],
  },
  sale: {
    type: "sale",
    name: "Sale Agreement / Agreement to Sell",
    description:
      "Fair sale agreement for property or assets with clear title warranty, fair payment terms, and RERA compliance. Protects both buyer and seller equally.",
    icon: "FileText",
    fields: saleFields,
    applicableLaws: [
      { name: "Transfer of Property Act", section: "1882, Sec 54", relevance: "Sale of immovable property" },
      { name: "RERA", section: "2016", relevance: "Real estate buyer protection" },
      { name: "Registration Act", section: "1908, Sec 17", relevance: "Compulsory registration" },
      { name: "Indian Stamp Act", section: "1899", relevance: "Stamp duty on sale deed" },
      { name: "Sale of Goods Act", section: "1930", relevance: "For movable property sales" },
    ],
  },
  service: {
    type: "service",
    name: "Service / Consultancy Agreement",
    description:
      "Fair service agreement for consultants, agencies, and professional service providers. Clear scope, fair payment, equal termination rights.",
    icon: "Settings",
    fields: serviceFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872", relevance: "Service contract validity" },
      { name: "Copyright Act", section: "1957, Sec 17", relevance: "Work product ownership" },
      { name: "Income Tax Act", section: "1961, Sec 194J", relevance: "TDS on professional services" },
      { name: "GST Act", section: "2017", relevance: "GST on services" },
      { name: "Consumer Protection Act", section: "2019", relevance: "Service deficiency" },
    ],
  },
  mou: {
    type: "mou",
    name: "Memorandum of Understanding (MOU)",
    description:
      "Clear MOU for exploring partnerships, joint ventures, or collaborations. Properly distinguishes binding and non-binding clauses under Indian law.",
    icon: "FileSignature",
    fields: mouFields,
    applicableLaws: [
      { name: "Indian Contract Act", section: "1872, Sec 10", relevance: "What makes an agreement binding" },
      { name: "Indian Contract Act", section: "1872, Sec 2(e)", relevance: "Agreement vs contract distinction" },
      { name: "Specific Relief Act", section: "1963", relevance: "Enforcement of binding terms" },
      { name: "IT Act", section: "2000, Sec 72A", relevance: "Confidentiality obligations" },
    ],
  },
  poa: {
    type: "poa",
    name: "Power of Attorney (POA)",
    description:
      "Secure Power of Attorney with specific powers, limited duration, and proper safeguards. Includes NRI provisions and registration requirements.",
    icon: "Stamp",
    fields: poaFields,
    applicableLaws: [
      { name: "Powers of Attorney Act", section: "1882", relevance: "POA creation and validity" },
      { name: "Registration Act", section: "1908, Sec 33", relevance: "Registration for property POA" },
      { name: "Indian Stamp Act", section: "1899", relevance: "Stamp duty on POA" },
      { name: "Transfer of Property Act", section: "1882", relevance: "Property transactions via POA" },
      { name: "Indian Contract Act", section: "1872, Sec 201-210", relevance: "Agency law" },
    ],
  },
};

/**
 * Get template config by type
 */
export function getTemplateConfig(type: ContractTemplateType): TemplateConfig | null {
  return TEMPLATE_CONFIGS[type] || null;
}

/**
 * Get all available (non-empty) template configs
 */
export function getAvailableTemplates(): TemplateConfig[] {
  return Object.values(TEMPLATE_CONFIGS).filter((t) => t.fields.length > 0);
}

/**
 * Get all template configs including coming soon
 */
export function getAllTemplates(): TemplateConfig[] {
  return Object.values(TEMPLATE_CONFIGS);
}

/**
 * Get grouped fields for form rendering
 */
export function getGroupedFields(fields: TemplateField[]): Record<string, TemplateField[]> {
  const groups: Record<string, TemplateField[]> = {};
  for (const field of fields) {
    const group = field.group || "Other";
    if (!groups[group]) groups[group] = [];
    groups[group].push(field);
  }
  return groups;
}