// ============================================
// CERTIFICATE TEMPLATE
// Section 65B certificate PDF using jsPDF
// ============================================

import jsPDF from "jspdf";
import type { Section65BData } from "@/types/evidence";

/**
 * Generate a Section 65B certificate PDF
 */
export function generateCertificatePdf(data: Section65BData): Buffer {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageWidth, pageHeight, "F");

  // Border
  pdf.setDrawColor(30, 30, 30);
  pdf.setLineWidth(0.5);
  pdf.rect(margin - 5, margin - 5, contentWidth + 10, pageHeight - margin * 2 + 10, "S");

  // Inner border
  pdf.setLineWidth(0.2);
  pdf.rect(margin - 3, margin - 3, contentWidth + 6, pageHeight - margin * 2 + 6, "S");

  // Title
  pdf.setFontSize(14);
  pdf.setTextColor(0, 0, 0);
  pdf.text("CERTIFICATE UNDER SECTION 65B(4)", pageWidth / 2, y + 5, { align: "center" });
  y += 10;

  pdf.setFontSize(11);
  pdf.text("OF THE INDIAN EVIDENCE ACT, 1872", pageWidth / 2, y + 4, { align: "center" });
  y += 15;

  // Horizontal rule
  pdf.setDrawColor(0, 0, 0);
  pdf.setLineWidth(0.3);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Body
  const addParagraph = (text: string, fontSize = 10, indent = 0) => {
    pdf.setFontSize(fontSize);
    pdf.setTextColor(20, 20, 20);
    const lines = pdf.splitTextToSize(text, contentWidth - indent);
    for (const line of lines) {
      if (y > pageHeight - margin - 10) {
        pdf.addPage();
        y = margin;
        pdf.setFillColor(255, 255, 255);
        pdf.rect(0, 0, pageWidth, pageHeight, "F");
      }
      pdf.text(line, margin + indent, y);
      y += 5;
    }
    y += 3;
  };

  addParagraph(
    `I, ${data.person_in_charge_name}, ${data.person_in_charge_designation}, ` +
    `residing at ${data.person_in_charge_address}, do hereby certify as follows:`
  );

  y += 3;

  addParagraph(
    "1. The electronic record described below was produced by a computer/device " +
    "during the period in which it was used regularly to store or process information:",
    10, 5
  );

  addParagraph(`Description: ${data.electronic_record_description}`, 9, 10);
  addParagraph(`Original Format: ${data.original_format}`, 9, 10);
  addParagraph(`Production Manner: ${data.production_manner}`, 9, 10);

  addParagraph(
    "2. The information contained in the electronic record was supplied to the computer " +
    "in the ordinary course of the activities of:",
    10, 5
  );
  addParagraph(data.information_derived_from, 9, 10);

  addParagraph(
    "3. The computer/device was operating properly during the material period. " +
    "If not, the malfunction did not affect the electronic record or its accuracy.",
    10, 5
  );
  addParagraph(`Device Description: ${data.device_description}`, 9, 10);

  addParagraph(
    "4. The electronic record is a reproduction/derivation of the information " +
    "fed into the computer in the ordinary course of activities.",
    10, 5
  );

  y += 5;
  pdf.setDrawColor(0, 0, 0);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Integrity section
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.text("INTEGRITY VERIFICATION", margin, y);
  y += 8;

  addParagraph(`${data.hash_algorithm} Hash: ${data.content_hash}`, 9);
  addParagraph(`Timestamp: ${data.timestamp_proof || "Local system timestamp"}`, 9);
  addParagraph(`Storage Medium: ${data.storage_medium}`, 9);

  y += 5;
  pdf.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Signature block
  addParagraph(`Date: ${data.date_of_certificate}`);
  addParagraph(`Place: ${data.place_of_certificate}`);
  y += 10;

  pdf.text("Signature: ____________________________", margin, y);
  y += 8;
  pdf.text(`Name: ${data.person_in_charge_name}`, margin, y);
  y += 5;
  pdf.text(`${data.person_in_charge_designation}`, margin, y);

  // Footer
  pdf.setFontSize(7);
  pdf.setTextColor(120, 120, 120);
  pdf.text("Generated by ClauseWall Evidence Chain Builder", pageWidth / 2, pageHeight - 10, { align: "center" });

  const pdfOutput = pdf.output("arraybuffer");
  return Buffer.from(pdfOutput);
}
